- hosts: localhost
  gather_facts: no
  become: yes
  vars:
    my_dir1: "/tmp/ansible_examples/G1\\$"
    my_dir2: '/tmp/ansible_examples/G2\$'
    # my_dir3: "/tmp/ansible_examples/G3\$"  # found unknown escape character
  tasks:
    - file:
        state: directory
        path: "{{ item }}"
      loop:
        - "{{ my_dir1 }}"
        - "{{ my_dir2 }}"

# > ls -1 /tmp/ansible_examples/
# 'G1\$'
# 'G2\$'

# Ansible Playbook: Escape '$' in Linux path
# https://stackoverflow.com/questions/56335948/ansible-playbook-escape-in-linux-path
