- hosts: localhost
  tasks:

    - command: env > enc.command
      args:
        chdir: /tmp/ansible_examples/testFolder/
      tags: t1

    - command: sh -c "env > enc.sh"
      args:
        chdir: /tmp/ansible_examples/testFolder/
      tags: t2

    - shell: jar -cf test.war *
      args:
        chdir: /tmp/ansible_examples/testFolder/
      tags: t3

    - shell: ls -1 *
      args:
        chdir: /tmp/ansible_examples/testFolder/
      tags: t4
