- hosts: test_11
  gather_facts: no
  tasks:
    - stat:
        path: /tmp/ansible_examples/test
      register: result
    - debug:
        msg: File exists
      when: result.stat.exists
    - stat:
        path: /tmp/ansible_examples/testX
      register: result
    - debug:
        msg: File does not exist
      when: not result.stat.exists
