- hosts: localhost
  gather_facts: false
  vars:
    lbrackets: "{{ '{{' }}"
    rbrackets: "{{ '}}' }}"
    quote: "'"
  tasks:
    - replace:
        path: "/tmp/ansible_examples/test"
        regexp: '^my_var = ""(.*)$'
        replace: '{{ "my_var = " ~
                     lbrackets ~ "getv " ~ quote ~
                     "/staging/my_dir/my_file" ~ quote ~ rbrackets
                     }}'

# Ansible/Jinja2 nested escaping
# https://stackoverflow.com/questions/58481609/ansible-jinja2-nested-escaping/

# $ cat /tmp/ansible_examples/test
# my_var = {{getv '/staging/my_dir/my_file'}}
