- hosts: localhost
  gather_facts: no
  vars:
    dirs:
      - /tmp/ansible_examples/01
      - /tmp/ansible_examples/01/a/b/c
      - /tmp/ansible_examples/01/b/c/d
      - /tmp/ansible_examples/01/c/d/e
  tasks:
    - name: Create directories
      command: mkdir -p "{{ item }}"
      args:
        creates: "{{ item }}"
      loop: "{{ dirs }}"
