---
- hosts: localhost
  become: false
  tasks:
    - name: read from CSV
      read_csv:
        path: cvs-01-data.csv
      register: users

    - debug:
        var: users

    - debug:
        msg: "{{ users.list|json_query('[*].name') }}"


# shell> cat cvs-01-data.csv
# name,uid,gid,password
# eg1,1,2,password
# eg2,1,2,password

#   users:
#     changed: false
#     dict: {}
#     failed: false
#     list:
#     - gid: '2'
#       name: eg1
#       password: password
#       uid: '1'
#     - gid: '2'
#       name: eg2
#       password: password
#       uid: '1'

#   msg:
#   - eg1
#   - eg2


# Ansible Error: 'list object' has no attribute 'name' when using read_csv module
# https://stackoverflow.com/questions/57506148/ansible-error-list-object-has-no-attribute-name-when-using-read-csv-module/
