- hosts: localhost
  gather_facts: false
  tasks:
    - shell: "echo {{ lookup('pipe', '/tmp/ansible_examples/my_script') }}"
#   - shell: "/tmp/ansible_examples/my_script"
      ignore_errors: true
      register: result
      until: result.stdout == 'OK'
      retries: 3
      delay: 2

    - debug:
        var: result
