---
- hosts: localhost
  gather_facts: false

  vars:

    versions:
      - "0.1.0"
      - "0.1.5"
      - "0.11.11"
      - "0.9.11"
      - "0.9.3"
      - "0.10.2"
      - "0.6.1"
      - "0.6.0"
      - "0.11.0"
      - "0.6.5"

  tasks:

    - debug:
        msg: "{{ versions | community.general.version_sort }}"

# How to sort complex version numbers in Ansible
# https://stackoverflow.com/questions/56063612/how-to-sort-complex-version-numbers-in-ansible/56064250#56064250
#
#   msg:
#   - 0.1.0
#   - 0.1.5
#   - 0.6.0
#   - 0.6.1
#   - 0.6.5
#   - 0.9.3
#   - 0.9.11
#   - 0.10.2
#   - 0.11.0
#   - 0.11.11
