---
- hosts: localhost
  gather_facts: false

  vars:

    ansible_versions:
      - '2.8.0'
      - '2.11.0'
      - '2.7.0'
      - '2.10.0'
      - '2.9.0'

  tasks:

    - debug:
        var: ansible_versions | community.general.version_sort

# ok: [localhost] => 
#   ansible_versions | community.general.version_sort:
#   - 2.7.0
#   - 2.8.0
#   - 2.9.0
#   - 2.10.0
#   - 2.11.0
